sudo: required
services:
  - docker

before_install:
# build the client container with a tag, de build directory is not the dot but the ./client
  - docker build -t webbylin/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run webbylin/docker-test npm run test -- --coverage

after_success:
  - docker build -t webbylin/multi-client ./client
  - docker build -t webbylin/multi-nginx ./nginx
  - docker build -t webbylin/multi-server ./server
  - docker build -t webbylin/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push webbylin/multi-client
  - docker push webbylin/multi-nginx
  - docker push webbylin/multi-server
  - docker push webbylin/multi-worker


# deploy:
#   provider: elasticbeanstalk
#   region: "eu-central-1"
#   app: "docker-react"
#   env: "DockerReact-env"
#   bucket_name: "elasticbeanstalk-eu-central-1-100164877691"
#   bucket-path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"


